name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: ✨ CI Pipeline for Unity Test Runner ✨
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Run playmode tests
      - name: Run playmode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: playmode
          resultPath: TestResults_PlayMode.xml

      # Upload playmode test results
      - name: Upload playmode test results
        uses: actions/upload-artifact@v3
        with:
          name: PlayModeTestResults
          path: TestResults_PlayMode.xml

      
      # Run editmode tests
      - name: Run editmode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: editmode
          resultPath: TestResults_EditMode.xml

      # Upload editmode test results
      - name: Upload editmode test results
        uses: actions/upload-artifact@v3
        with:
          name: EditModeTestResults
          path: TestResults_EditMode.xml
